# Generated by Django 3.2.20 on 2023-08-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('organization_name', models.CharField(default=None, max_length=100)),
                ('phone_number', models.PositiveBigIntegerField(default=None)),
                ('description', models.TextField(default=None)),
                ('is_terms_and_conditions_agreed', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'In Progress'), (4, 'Cancelled')], default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField()),
                ('pincode', models.IntegerField()),
                ('phone_number', models.PositiveBigIntegerField()),
                ('join_date', models.DateField(blank=True, null=True)),
                ('created_date_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.area')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sign_up_terms_and_conditions', models.TextField()),
                ('booking_terms_and_conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.country')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLocationWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('work_from_time', models.TimeField()),
                ('work_to_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('organization_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.organizationlocation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLocationGameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.gametype')),
                ('organization_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.organizationlocation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLocationAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parking', models.BooleanField(default=False)),
                ('is_restrooms', models.BooleanField(default=False)),
                ('is_changerooms', models.BooleanField(default=False)),
                ('is_powerbackup', models.BooleanField(default=False)),
                ('is_beverages_facility', models.BooleanField(default=False)),
                ('is_coaching_facilities', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('organization_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.organizationlocation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationGameImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.organizationlocationgametype')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.tenant'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.PositiveBigIntegerField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.tenant'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.state')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.city'),
        ),
    ]
