# Generated by Django 3.2.20 on 2023-08-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='alt_number',
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
