# Generated by Django 3.2.20 on 2023-08-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='location',
        ),
    ]
