# Generated by Django 3.2.20 on 2023-08-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_tenant_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationlocation',
            name='work_from_time',
        ),
        migrations.RemoveField(
            model_name='organizationlocation',
            name='work_to_time',
        ),
    ]
