# Generated by Django 3.2.20 on 2023-08-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_organization_alt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='alt_number',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
