# Generated by Django 3.2.20 on 2023-08-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20230811_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationAmenities',
            new_name='OrganizationLocationAmenities',
        ),
        migrations.RenameField(
            model_name='organizationlocationamenities',
            old_name='organization',
            new_name='organization_location',
        ),
    ]
