# Generated by Django 3.2.20 on 2023-08-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20230823_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='area_name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='gametype',
            old_name='name',
            new_name='game_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='state_name',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='name',
            new_name='tenant_name',
        ),
    ]
