# Generated by Django 3.2.20 on 2023-08-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20230811_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LocationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.locationcity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.tenant')),
            ],
        ),
    ]
