# Generated by Django 3.2.20 on 2023-08-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_locationarea_locationcity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationlocationgametype',
            name='price_calculate_timing',
        ),
        migrations.RemoveField(
            model_name='organizationlocationgametype',
            name='pricing',
        ),
    ]
