# Generated by Django 3.2.20 on 2023-08-24 09:55

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_organizationlocation_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlocation',
            name='area_name',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='area_name', chained_model_field='area', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.area'),
        ),
        migrations.AddField(
            model_name='organizationlocation',
            name='city_name',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='city_name', chained_model_field='city', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.city'),
        ),
        migrations.AddField(
            model_name='organizationlocation',
            name='country_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.country'),
        ),
        migrations.AddField(
            model_name='organizationlocation',
            name='state_name',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='country_name', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.state'),
        ),
    ]
