# Generated by Django 3.2.20 on 2023-08-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20230811_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlocationgametype',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
