# Generated by Django 3.2.20 on 2023-08-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_organizationlocationgametype_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationlocationamenities',
            name='organization_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.organizationlocation'),
        ),
    ]
