# Generated by Django 3.2.20 on 2023-08-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_organizationlocationamenities_organization_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationlocationworkingdays',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.organizationlocation'),
        ),
    ]
