# Generated by Django 3.2.20 on 2023-08-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20230824_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='city',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='state',
            new_name='state_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='country',
            new_name='country_name',
        ),
    ]
