# Generated by Django 3.2.20 on 2023-08-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20230824_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationLocationWorkingDays',
        ),
    ]
