# Generated by Django 3.2.20 on 2023-08-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_testcustomer_testlocationarea_testlocationcity_testorganization_testorganizationlocation_testorganiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testorganization',
            name='alt_number',
        ),
        migrations.RemoveField(
            model_name='testorganization',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='testorganization',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='testorganization',
            name='description',
            field=models.TextField(default='No Description set yet.'),
        ),
    ]
