# Generated by Django 3.2.20 on 2023-08-28 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_delete_organizationlocationworkingdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLocationWorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_from_time', models.TimeField()),
                ('primary_to_time', models.TimeField()),
                ('secondary_from_time', models.TimeField(blank=True, null=True)),
                ('secondary_to_time', models.TimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.organizationlocation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLocationWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('timing', models.IntegerField(choices=[(0, 'Primary Time Slot'), (1, 'Secondary Time Slot')])),
                ('workingtimes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.organizationlocationworkingtime')),
            ],
        ),
    ]
