# Generated by Django 3.2.20 on 2023-08-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_testorganization_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorganization',
            name='organization_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
