# Generated by Django 3.2.20 on 2023-08-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_organizationlocationworkingday_organizationlocationworkingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organizationlocationworkingday',
            name='timing',
            field=models.BooleanField(),
        ),
    ]
