# Generated by Django 3.2.20 on 2023-08-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20230828_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
