# Generated by Django 3.2.20 on 2023-08-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_organization_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationlocationworkingtime',
            name='organization',
        ),
        migrations.DeleteModel(
            name='OrganizationLocationWorkingDay',
        ),
        migrations.DeleteModel(
            name='OrganizationLocationWorkingTime',
        ),
    ]
