# Generated by Django 3.2.20 on 2023-08-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20230828_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLocationWorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_day_choices', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('organization_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.organizationlocation')),
            ],
        ),
    ]
