# Generated by Django 3.2.20 on 2023-08-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_organizationlocationworkingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationlocationworkingtime',
            name='from_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationlocationworkingtime',
            name='to_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationlocationworkingtime',
            name='work_day_choices',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
    ]
